name: Greetings

on:
  issues:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    name: Greetings
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '<h2>Hey there! :hooray: </h2>Thanks for raising an issue! Keep contributing - open a PR on this repo and get an extra green square!<br><br>P.S. Don''t forget to link the PR to this issue!'
