name: Greetings

on:
  issues:
  pull_request:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    name: Greetings
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '<h2>Hey there! :laugh: </h2>Thanks for raising an issue, keep contributing!'
        pr-message: '<h2>Awesome! :hooray: <h2>You made PR on this repo, keep up the good work! Don''t forget to link it to an issue!'
